import type { Transaction } from "@/lib/types";

export const demoTransactions: Transaction[] = [
  {
    id: "demo-001",
    date: "2026-06-02",
    bank: "QNB",
    descriptionRaw: "POS TALABAT DOHA QA",
    merchant: "TALABAT",
    amount: 84.5,
    direction: "expense",
    currency: "QAR",
    category: "Ordering Out",
    subcategory: "Food Delivery",
    confidence: 0.95,
    reason: "Matched merchant rule \"talabat\".",
    needsReview: false,
    categorySource: "default_rule",
    duplicateHash: "demo-001"
  },
  {
    id: "demo-002",
    date: "2026-06-03",
    bank: "QNB",
    descriptionRaw: "CARREFOUR VILLAGGIO",
    merchant: "CARREFOUR VILLAGGIO",
    amount: 312.2,
    direction: "expense",
    currency: "QAR",
    category: "Groceries",
    subcategory: "Supermarket",
    confidence: 0.95,
    reason: "Matched merchant rule \"carrefour\".",
    needsReview: false,
    categorySource: "default_rule",
    duplicateHash: "demo-002"
  },
  {
    id: "demo-003",
    date: "2026-06-05",
    bank: "CBQ",
    descriptionRaw: "SALARY TRANSFER",
    merchant: "SALARY",
    amount: 21000,
    direction: "income",
    currency: "QAR",
    category: "Salary / Income",
    subcategory: "Salary",
    confidence: 0.9,
    reason: "Matched merchant rule \"salary\".",
    needsReview: false,
    categorySource: "default_rule",
    duplicateHash: "demo-003"
  },
  {
    id: "demo-004",
    date: "2026-06-08",
    bank: "CBQ",
    descriptionRaw: "OOREDOO MOBILE PAYMENT",
    merchant: "OOREDOO MOBILE",
    amount: 240,
    direction: "expense",
    currency: "QAR",
    category: "Bills",
    subcategory: "Mobile",
    confidence: 0.95,
    reason: "Matched merchant rule \"ooredoo\".",
    needsReview: false,
    categorySource: "default_rule",
    duplicateHash: "demo-004"
  },
  {
    id: "demo-005",
    date: "2026-06-11",
    bank: "QNB",
    descriptionRaw: "UBER TRIP",
    merchant: "UBER TRIP",
    amount: 38,
    direction: "expense",
    currency: "QAR",
    category: "Transport",
    subcategory: "Ride Hailing",
    confidence: 0.88,
    reason: "Matched merchant rule \"uber\".",
    needsReview: false,
    categorySource: "default_rule",
    duplicateHash: "demo-005"
  },
  {
    id: "demo-006",
    date: "2026-06-14",
    bank: "QNB",
    descriptionRaw: "VILLAGGIO MALL STORE",
    merchant: "VILLAGGIO MALL STORE",
    amount: 690,
    direction: "expense",
    currency: "QAR",
    category: "Malls",
    subcategory: "Mall Purchase",
    confidence: 0.53,
    reason: "Low-confidence mall classification. Review once and save a rule.",
    needsReview: true,
    categorySource: "fallback",
    duplicateHash: "demo-006"
  }
];
